# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"
  config.vm.network :private_network, ip: "192.168.33.10"
  #config.vm.network "forwarded_port", guest: 3306, host: 3306
  config.vm.provision :shell, :path => 'provision.sh'
  config.ssh.insert_key = false
end
