# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"

  (1..3).each do |seq|
    config.vm.define "g#{seq}" do |db|
      db.vm.hostname = "g#{seq}"
      db.vm.provider "virtualbox" do |vm|
        vm.gui = false
        vm.memory = 256
      end
      db.vm.network :private_network, ip: "192.168.33.#{10 + seq}"
      db.vm.provision :shell, :path => 'provision.sh', :args => [seq, "192.168.33.#{10 + seq}"]
      db.ssh.insert_key = false
    end
  end
end
