# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # You must download Vagrant Box from https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
  # and add it with name "ie11win7".
  config.vm.box = "ie11win7"

  config.vm.provider "virtualbox" do |vb|
    vb.gui = true
  end
  config.ssh.insert_key = false
  config.vm.boot_timeout = 1
  config.vm.network :private_network, ip: "192.168.33.100"
end
