# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "boxcutter/centos71"

  (1..3).each do |seq|
    config.vm.define "es#{seq}" do |es|
      es.vm.network :private_network, ip: "192.168.33.#{10 + seq}"
      es.vm.provision :shell, :path => 'provision.sh'
      es.ssh.insert_key = false
    end
  end
end
