# -*- mode: ruby -*-
# vi: set ft=ruby :

VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = "precise64"

  master_address = "192.168.33.21"
  config.vm.define "master" do |db|
    db.vm.hostname = "master"
    db.vm.provider "virtualbox" do |vm|
      vm.gui = false
      vm.memory = 256
    end
    db.vm.network :private_network, ip: master_address
    db.vm.provision :shell, :path => 'master.sh'
    db.ssh.insert_key = false
  end
  (1..2).each do |seq|
    config.vm.define "slave#{seq}" do |db|
      db.vm.hostname = "slave#{seq}"
      db.vm.provider "virtualbox" do |vm|
        vm.gui = false
        vm.memory = 256
      end
      db.vm.network :private_network, ip: "192.168.33.#{21 + seq}"
      db.vm.provision :shell, :path => 'slave.sh', :args => [seq + 1, master_address]
      db.ssh.insert_key = false
    end
  end
end
